# Adds the 'triage' label to newly opened issues

name: Add triage label to new issues
on:
  issues:
    types: [opened]

jobs:
  add_triage_label:
    runs-on: ubuntu-latest
    steps:
      - name: Add triage label
        uses: actions/github-script@v6
        with:
          script: |
            await github.rest.issues.addLabels({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              labels: ["triage"]
            });
